### PR TITLE
Fix #371

### LINKED ISSUE #371: Verify all the Javadoc comments
During the release for Roboconf 0.4, we encountered issues due to invalid Javadoc comments.
Even if we skip this kind of validation in releases now, we should verify the correctness of our Javadoc.

We can use [mvn javadoc:javadoc](https://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html) or [mvn javadoc:fix](https://maven.apache.org/plugins/maven-javadoc-plugin/fix-mojo.html) to achieve this. Relying on the Javadoc profile in Roboconf (**jdoc-and-sources**) seems useless IMO.

### PR DESCRIPTION
**Pull request by bourretp**
Fix #371 + bump to parent pom 1.5-SNAPSHOT (that will include javadoc configuration)

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
We don't use snapshots parent.
Submit a PR about the parent 1.5. Once accepted, release it to Maven Central, et switch the platform to this new version.

**Comment by bourretp** [comment]
Ok.
I was also wondering where to add the `-Droboconf.javadoc.check` option for Travis. travis-build.sh command line and Travis logs seem unrelated...

**Comment by vincent-zurczak** [comment]
Not sure to understand the last comment.
To enable Javadoc check on Travis with Java 8, just add...

```bash
elif [[ $VER == "18" ]]; then
	mvn clean install -Droboconf.javadoc.check
```

... in the **travis-build.sh** file.

**Comment by bourretp** [comment]
Ooops, my bad. Javadoc check profile is active, but the `javadoc:javadoc` goal is not run.
My bad...

**Comment by vincent-zurczak** [comment]
Indeed. And please, enable it only with Java 8.

**Comment by bourretp** [comment]
Clear to merge (?)

**Comment by bourretp** [comment]
Induced by your previous comment... but yes! I actually did... :innocent:

**Comment by vincent-zurczak** [comment]
Travis builds run with the -q flag.
Did you try it locally with a Javadoc error? Does it fail the build? I think so, but that's just to be sure.

**Comment by bourretp** [comment]
Don't worry, tested and approved :+1:

**Pull request merged**
