### PR TITLE
Websocket support in the DM

### PR DESCRIPTION
**Pull request by vincent-zurczak**
... plus lots of new tests.  :sunflower:

### CODE REVIEW

**Comment by vincent-zurczak** [comment]
OK. We really need to upgrade our integration tests.
Debugging them is a nightmare. :fearful:

**Comment by gibello** [comment]
Code looks fine, but what about the continuous integration failure ? Requires to be fixed... or ignored ??

**Comment by vincent-zurczak** [comment]
I am working on integration tests to fix the build... and a serious bug.
Integration tests generate a bundle on the fly with all the test classes. The last IT I added are the cause of conflicts when these tests run in Maven (they are working fine in Eclipse). I am working on generating a bundle with only the current test class. This will prevent conflicting requirements between tests. I will push a new commit this evening to fix that.

Merging can wait your return on Friday.

**Comment by vincent-zurczak** [comment]
OK. I'm done working on integration tests.
Everything's not perfect, but that will be good for now.

**Pull request merged**
